version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'Europe/Zurich'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /home/homeserver/data/samba/printer:/mnt:z
    command: '-S -s "Printer;/mnt;yes;no;no;bob" -u "bob;oukerie" -p'

networks:
  default:

