- Oukflix Download:
    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.oukcorp.com/
        description: Series management
        ping: http://sonarr:8989
        container: sonarr
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: c41841f3005c401f86c8529ee7844094

    - Radarr:
        icon: radarr.png
        href: https://radarr.oukcorp.com/
        description: Movie management
        ping: http://radarr:7878
        container: radarr
        widget:
          type: radarr
          url: http://radarr:7878
          key: 509d0fa395d540eca81e31a01c6469f0

    - Prowlarr:
        icon: prowlarr.png
        href: https://prowlarr.oukcorp.com/
        ping: http://prowlarr:9696
        container: prowlarr
        widget:
        type: prowlarr
        url: http://prowlarr:9696
        key: 0e5c6b0c242543e7be604bb3b0789779


    - Bazarr:
        icon: bazarr.png
        href: https://bazarr.oukcorp.com/
        ping: http://bazarr:6767
        container: bazarr
        widget:
          type: bazarr
          url: http://bazarr:6767
          key: 23afc48f5f94e959b130975ab0fee309

    - Qbittorrent:
        icon: qbittorrent.png
        href: https://qb.oukcorp.com/
        ping: http://qbittorrent:8080
        container: qbittorrent
        widget:
          type: qbittorrent
          url: http://qbittorrent:8080
          username: admin
          password: tz6R$8cjRXx3d^LVy!6i9Pz2ku


- Oukflix Watch:
    - Jellyfin:
        icon: jellyfin.png
        href: https://jl.oukcorp.com/
        ping: http://jellyfin:8096
        container: jellyfin
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: eaa283dc3453402fbfc1299caca575d2	
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true

    - Jellyseerr:
        icon: jellyseerr.png
        href: https://jsr.oukcorp.com/
        ping: http://jellyseerr:5055
        container: jellyseerr
        widget:
          type: jellyseerr
          url: http://jellyseerr:5055
          key: MTcwMjU5MTMxMTcwNTU2YWZjMjFjLWM2YjctNDk4Ny1hNDZiLTRmNDdmZGY1ODNlZA==

- Monitoring:
    - Portainer:
        icon: portainer.png
        href: https://pr.oukcorp.com/
        ping: http://portainer:9000
        container: portainer
        widget:
          type: portainer
          url: http://portainer:9000
          env: 2
          key: ptr_EKeEhLqnj6NdY2qitZ7eBmL6T0b8imau50Z0N9jJb8Q=

    - Grafana:
        icon: grafana.png
        href: https://grafana.oukcorp.com/
        ping: http://grafana:3000
        container: grafana
        #widget:
        #  type: grafana
        #  url: http://grafana:3000
        #  username: admin
        #  password: &xrX#Xyh@UBun3MLc28Yia9jW6L^VR

    - Traefik:
        icon: traefik.png
        href: https://traefik.oukcorp.com/
        #ping: http://traefik:8080
        container: traefik
        #widget:
        #  type: traefik
        #  url: http://traefik:8080

    #- Kuma:
    #    icon: uptime-kuma.png
    #    href: https://kuma.oukcorp.com
    #    ping: http://uptime-kuma:3001
    #    container: uptime-kuma

- Self-Host:

    - Immich:
        icon: immich.png
        href: https://immich.oukcorp.com
        ping: immich_server:2283
        container: immich_server
        widget:
            type: immich
            url: http://immich_server:2283
            key: SM3QbIRaOgxpW50cocyx3UUupIM0KKYjYxyLPd5A
    #- Pi-Hole:
     #   icon: pi-hole.png
    #    href: https://pi.oukcorp.com/
    #    ping: http://pihole:80
    #    container: pihole
    #    widget:
    #      type: pihole
    #      url: http://pihole:80
    #      key: 458f77e2c27c00cac7f1710e8ff1be5964030bc176dbf29c9c215a876489ddd5 # optional
        
    - Nextcloud:
        icon: nextcloud.png
        href: https://nextcloud.oukcorp.com/
        ping: http://nextcloud:443
        container: nextcloud
        widget:
          type: nextcloud
          url: http://nextcloud:443
          username: Fencing7589
          password: 7ah@jahB2#5*%m7EM#C%F7QXYETXJZ
    #- Vaultwarden:
     #   icon: vaultwarden.png
      #  href: https://vw.oukcorp.com/
       # ping: http://vaultwarden:80
        #container: vaultwarden

    - Paperless:
        icon: paperless-ngx.png
        href: https://paper.oukcorp.com/
        ping: http://paperless:8000
        container: paperless
        widget:
            type: paperlessngx
            url: http://paperless:8000
            key: 33056aff79220db11668d3b2d7f61561069b89d3

    

